app/Http/routes.php
<?php

Route::get('pack_items',function (){
    return \App\Packages\Package::packages_with_items();
});
//for test the api
Route::get('test',function (){
    return view('dashboard.website.steps.upgrade');
});
Route::auth();
Route::get('clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    return 'cache cleared';
});
Route::get('country_collection', function() {
    $countries = Cache::get('countries');
    $cid = 60;
    return $countries->where('id',$cid)->first()->name;
});
Route::get('mail_tester', function() {

    $send_to = 'marwan.nabil.mohamed@gmail.com';
    $data = array('name'=>"Yalla Tester", "body" => "This is a Test mail", 'email'=>$send_to);

    Mail::send('front.emails.tester_mail', $data, function($message) use ($send_to) {
        $message->to($send_to, 'Tester mail')
            ->subject('Yalla Testing Mail');
        $message->from('yallansadar@gmail.com','Yallansadar');
    });

    return 'Mail should be sent to; ' .$send_to;
});
Route::get('slugging', function() {
    //Make slug strings for Request for Quotes
    $rfq = \App\Deals\QuoteRequest::all();
    foreach ($rfq as $row)
    {
        $row->slug = \App\Helper::generate_slug('\App\Deals\QuoteRequest', $row->service_product_name, $row->id);
        if($row->save()) {
            print($row->service_product_name.': <strong>('.$row->slug.')</strong> Done <br>');
        }
    }
    return ' ********************* End of script ********************';
});
Route::get('rfq_lang', function() {
    //Make slug strings for Request for Quotes
    $rfq = \App\Deals\QuoteRequest::with('lang')->get();
    foreach ($rfq as $row)
    {
        $row->details_en = $row->lang->where('language_id', 1)->first()->details;
        $row->details_ar = $row->lang->where('language_id', 2)->first()->details;
        if($row->save()) {
            print($row->service_product_name.' lang updated <br>');
        }
    }
    return ' ********************* End of script ********************';
});
Route::get('rfq_names_lang', function() {
    //Make slug strings for Request for Quotes
    $rfq = \App\Deals\QuoteRequest::all();
    foreach ($rfq as $row)
    {
        $row->name_ar = $row->service_product_name;
        $row->name_en = $row->service_product_name;
        if($row->save()) {
            print($row->service_product_name.' lang updated <br>');
        }
    }
    return ' ********************* End of script ********************';
});
Route::get('set_parent_cats_rfq', function() {
    //Get Parent Category and save for RFQ
    $rfq = \App\Deals\QuoteRequest::all();
    foreach ($rfq as $row)
    {
        $cats = App\Category::get_parents($row->category_id);
        if($cats && count($cats) > 0){
            foreach($cats as $cat) {
                if(!$cat){
                    continue;
                }
                if($cat->parent_category_id==0) {
                    $row->parent_cat_id = $cat->id;
                    break;
                }
            }

            if($row->save()) {
                print($row->service_product_name.': updated with cat '.$row->parent_cat_id.'<br>');
            }
        }
    }
    return ' ********************* End of script ********************';
});
Route::get('transfer_product_lang', function() {
    $products = \App\Product::with('lang')->get();
    foreach ($products as $row)
    {
        $row->name_en = @$row->lang->where('language_id', 1)->first()->name;
        $row->name_ar = @$row->lang->where('language_id', 2)->first()->name;
        $row->description_en = @$row->lang->where('language_id', 1)->first()->description;
        $row->description_ar = @$row->lang->where('language_id', 2)->first()->description;
        $row->details_en = @$row->lang->where('language_id', 1)->first()->details;
        $row->details_ar = @$row->lang->where('language_id', 2)->first()->details;
        $row->keywords_en = @$row->lang->where('language_id', 1)->first()->keywords;
        $row->keywords_ar = @$row->lang->where('language_id', 2)->first()->keywords;
        $row->packaging_en = @$row->lang->where('language_id', 1)->first()->packaging;
        $row->packaging_ar = @$row->lang->where('language_id', 2)->first()->packaging;

        if($row->save()) {
            print($row->name_ar.': updated <br>');
        }
    }
    return ' ********************* End of script ********************';
});
Route::get('slugging_products', function()
{
    //Make slug strings for Products
    $products = \App\Product::all();
    foreach ($products as $row)
    {
        $row->slug = \App\Helper::generate_slug('\App\Product', $row->name, $row->id);
        if($row->save()) {
            print($row->name.': <strong>('.$row->slug.')</strong> Done <br>');
        }
    }
    return ' ********************* End of script ********************';
});
Route::get('slugging_users', function()
{
    //Make slug strings for Users
    $users = \App\User::all();
    foreach ($users as $row)
    {
        if(!empty($row->company_name)) {
            $row->slug = \App\Helper::generate_slug('\App\User', $row->company_name, $row->id);
        } else {
            $user_profile = $row->profile;
            if($user_profile && !empty($user_profile->company_name)) {
                $row->slug = \App\Helper::generate_slug('\App\User', $user_profile->company_name, $row->id);
            } else {
                $row->slug = \App\Helper::generate_slug('\App\User', $row->name, $row->id);
            }
        }
        if($row->save()) {
            print('<strong>'.$row->slug.'</strong> <br>');
        }
    }
    return ' ********************* End of script ********************';
});
Route::get('see_mail', function() {
    $quote = \App\Deals\Quote::find(96);
    $deal = \App\Deals\QuoteRequest::find(41);
    $data = $deal->toArray();
    return view('front.emails.deals.rfq_mail', ['quote'=>$quote,'deal'=>$deal,'data'=>$data]);
});

Route::get('set_users_has_products', function() {
    $products = \App\Product::where('active',1)->where('approved',2)->with('user')->get();
    foreach($products as $product) {
        $product->user->has_products = 1;
        if($product->user->save()) {
            return $product->user->name.' set to has products';
        }
    }
    return ' ********************* End of script ********************';
});

Route::get('admin/generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@getGenerator']);

Route::post('admin/generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@postGenerator']);

// routes special for api request
Route::group(['prefix' => 'api' , 'namespace' => 'api'], function (){
    Route::post('login','UserController@login');
    Route::post('register','UserController@register');
    Route::get('/password/reset' , 'UserController@Reset');
    
    //now the route that need authentication first
    Route::group(['middleware' => 'api_auth'] , function (){
        Route::get('packages' , 'PackagesController@GetPackageAllDetails');
        Route::get('en/GetAllPorts' , function (){
           return \App\Helper::api_response_format(true , [
                'Alexandria', 'Suze', 'Abu Qir', 'Abu Zenima', 'Adabiya', 'Ain Sukhna', 'Damietta', 'El Dekheila', 'Kosseir', 'Maadiya Port', 'Nuweibah', 'Port Said', 'Ras Sudr', 'Za\'farana',
            ]);
        });
        Route::get('ar/GetAllPorts' , function (){
            return \App\Helper::api_response_format(true , [
                'الاسكندرية', 'السويس', 'ابو قير', 'ابو زنيمة', 'الادبية', 'العين السخنة', 'دمياط', 'الدقهلية', 'القصير', 'المعدية', 'نويبع', 'بور سعيد', 'رأس سدر', 'الزعفرانة',
            ]);
        });

        Route::post('upload/file' , 'FileCOntroller@uploadSingleFile');
        Route::post('upload/multifile' , 'FileCOntroller@uploadMulipleFile');
        Route::get('GetAllThemes' , 'ThemesController@GetAllThemese');
        Route::post('SelectTheme' , 'ThemesController@SelectTheme');
        Route::get('ar/paymentTerms',function (){
            return Response::json([
                'data' => ['T/T','L/C','D/P D/A','ماني جرام','كارت ائتمان','باي بال','ويسترن يونيون','كاش','شيك','Demand Draft','أخرى']
            ], 200);

        });

        Route::get('en/paymentTerms',function (){
            return Response::json([
                'data' => ['T/T' , 'L/C','D/P D/A','MoneyGram','Credit Card','PayPal','Western Union','Cash','Cheque','Demand Draft','Other']
            ], 200);
        });
        //to list all countries by limit
        Route::get('countries/{limit?}' , function ($limit = null){
            return \App\Country::limit($limit)->get();    
        });
        
        Route::get('product/categories' , function (\Illuminate\Http\Request $request){
            $categories = \App\Category::whereParent_category_id(0);
            $categories = \App\Helper::check_collection_limit($categories , $request->limit , $request->offset)->get(['name_ar' , 'id' , 'name_en']);
            foreach ($categories as $category){
                $category->childs = $category->childs_tree;
            }
            return $categories;
        });
        Route::post('setUserRole' , 'UserController@setUserRole');
        Route::post('countries/{iso}' , function ($iso){
            return \App\Country::whereIso2($iso)->get();    
        });
        //to activate accounts
        Route::get('activate' , 'UserController@send_activation');
        //get specific user
        Route::post('users/{id}','UserController@get_user');
        //update specific user
        Route::PUT('users/{id}','UserController@update_user');
//*****************************Profile*******************************U**********************
        // the user profiles specified with that user
        Route::get('user-profile/{id}','UserProfileController@get_profile');
          //create userProfile
        Route::post('user-profile','UserProfileController@create_profile');
          //update profile

app/Http/Controllers/Admin/ServicesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Service;
use App\Category;
use Session;

class ServicesController extends InitController
{
    public function __construct() {
    	parent::__construct();
    }

    public function index(Request $request)
    {
        $services = new Service;

        if($request->has('status') && $request->get('status')!=0) {
            $services = $services->whereStatus($request->get('status'));
        }

        $services = $services->orderBy('id', 'DESC')->paginate(10);
        return view('admin.services.index', compact('services'));
    }

    public function create()
    {
        return view('admin.services.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
			'category_id' => 'required',
			'user_id' => 'required',
			'name' => 'required'
		]);
        $requestData = $request->all();
        Service::create($requestData);

        Session::flash('flash_message', 'Service added!');
        return redirect('admin/services');
    }

    public function show($id)
    {
        $service = Service::whereId($id)->with('lang','category','images','user')->first();
        $category_parents = [];
        if($service->category) {
            $category_parents = Category::get_parents($service->category->id);
        }
        return view('admin.services.show', compact('service', 'category_parents'));
    }

    public function edit($id)
    {
        $service = Service::findOrFail($id);
        return view('admin.services.edit', compact('service'));
    }

    public function update($id, Request $request)
    {
        $this->validate($request, [
			'category_id' => 'required',
			'user_id' => 'required',
			'name' => 'required'
		]);
        $requestData = $request->all();
        
        $service = Service::findOrFail($id);
        $service->update($requestData);

        Session::flash('flash_message', 'Service updated!');
        return redirect('admin/services');
    }

    public function destroy($id)
    {
        Service::destroy($id);
        Session::flash('flash_message', 'Service deleted!');
        return redirect('admin/services');
    }
}

app/Http/Controllers/Front/CompaniesController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Company;
use App\User;

class CompaniesController extends InitController
{
    public function __construct()
    {
    	parent::__construct();
    }

    public function getSite($company_id, $slug)
    {
    	$company = Company::whereId($company_id)->with('user_products')->first();
    	return view('front.companies.website.index', compact('company'));
    }

    public function getContact($user_id)
    {
        $user = User::whereId($user_id)->with('profile')->first();
        return view('front.companies.contact_details', compact('user'));
    }

    public function getContactInfo($slug, $id=null)
    {
        $user = new User;
        if(is_numeric($slug)) {
            $user = $user->whereId($slug);
        } else {
            $user = $user->whereSlug($slug);
        }
    	$user = $user->with('profile')->first();
    	return view('front.companies.contact_page', compact('user'));
    }
}

app/Http/Controllers/Front/HomeController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Category;
use App\Product;
use App\Company;
use App\Testimontial;
use App\Slider;
use App\User;
use App\Service;
use App\Adv;
class HomeController extends InitController
{
    public function __construct()
    {
    	parent::__construct();
    }

    public function getHome()
    {
    	$categories = Category::get_tree(0, 30);
        $top_categories = Category::whereHp_top(1)->take(12)->get();
    	$testimontials = Testimontial::whereActive(1)->whereHomepage(1)->take(4)->get();
    	$slider = Slider::whereActive(1)->orderBy('id', 'DESC')->get();
        $hot_products = Product::whereActive(1)->whereApproved(2)->orderBy('id', 'DESC')->with('lang')->take(20)->get();
        $suppliers = User::whereActive(1)->whereFeatured(1)->orderBy('id', 'DESC')->take(6)->with('profile')->get();
        $services = Service::whereActive(1)->whereStatus(2)->orderBy('id','DESC')->with('lang')->take(6)->get();

        $export_categories = new \App\Deals\QuoteRequest;
        $export_categories = $export_categories->whereActive(1)->whereStatus(2)->groupBy('parent_cat_id');
        $export_categories = $export_categories->select(\DB::raw('count(*) as total_rfq, parent_cat_id'));
        $export_categories = $export_categories->with('parent_category');
        $export_categories = $export_categories->orderBy('total_rfq', 'DESC');
        $export_categories = $export_categories->take(9);
        $export_categories = $export_categories->get();

        $deals['sell_offers'] = \App\Deals\SellOffer::whereActive(1)->whereStatus(2)->with('user','images','product')->orderBy('id','DESC')->take(4)->get();
        $deals['quote_requests'] = \App\Deals\QuoteRequest::whereActive(1)->whereStatus(2)->with('user','images')->orderBy('id','DESC')->take(4)->get();
        $deals['partnerships'] = \App\Deals\Partnership::whereActive(1)->whereStatus(2)->with('user','images')->orderBy('id','DESC')->take(4)->get();

        $blog = \App\Blog::whereActive(1)->orderBy('updated_at', 'DESC')->take(3)->get();
        $advs = Adv::whereType('الصفحة الرئيسية')->whereActive(1)->get();
    	return view('front.index', compact('categories','top_categories', 'export_categories', 'testimontials', 'slider', 'hot_products', 'suppliers','deals', 'services', 'blog','advs'));
    }

    public function getMobileapps() {
        return view('front.mobileapp.soon');
    }

    public function getHelp() {
        return view('front.help.index');
    }

    public function getPrivacyPolicy() {
        return view('front.site.privacy.policy');
    }

    public function getTerms() {
        return view('front.site.privacy.terms');
    }

    public function getLanding() {
        if(\App::getLocale()=='ar'){
            return view('front.landing.page');
        } else {
            return view('front.landing.page_en');
        }        
    }

    public function getExporters() {
        $exporters = new User;
        $exporters = $exporters->whereActive(1)->whereExporter(1);
        $exporters = $exporters->groupBy('name');
        $exporters = $exporters->orderBy('name', 'ASC')->with('profile')->paginate(8);

        $latest_products = Product::whereActive(1)->whereApproved(2)->orderBy('id', 'DESC')->take(10)->get();        
        return view('front.companies.exporters', compact('exporters', 'latest_products'));
    }
   
}

app/Http/Controllers/Front/LanguagesController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Language;
use Cache;

class LanguagesController extends InitController
{
    public function __construct()
    {
    	parent::__construct();
    }

    public function getSwitch($locale='en')
    {
    	if(Language::switch_language($locale)) {
            Cache::forget('countries');

            if(request()->has('back') && request()->get('back')=='no') {
                return redirect()->to('/');
            }
    		return redirect()->back();
    	}
    	return 'Cannot change system language';
    }
}

resources/views/front/services/show.blade.php
<?php
	use App\User;
	use App\Category;
	use App\Service;
	use App\Company;
	use App\Helper;
	$parents = array_reverse($category_parents);
	$service_lang = Helper::lang_data($service, $lng_id);
	$profile = $service->user->profile;
	if(!$service_lang) {
		return redirect()->back();
	}

	$business_types = ($profile->business_type) ? explode(',', $profile->business_type):'';
	$service_locations = (!empty($service->locations)) ? explode(',',$service->locations): [];
?>
@extends('front.layouts.master')
@section('title') {{$service_lang->name}} | @endsection
@section('content')
<div class="">
	<ul class="container breadcrumb">
	  	<li><a href="{{url('/')}}">{{trans('front.home')}}</a></li>
	  	@if(!empty($parents))
		  	@foreach($parents as $cat)
				<li><a href="{{Category::url($cat)}}">{{@$cat->$c_name}}</a></li>
			@endforeach
		@endif
		<li class="active">{{$service_lang->name}}</li>
	</ul>
</div>

<div class="inner-pg-cntnr">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-md-4">
                <div class="sp-loading">{{HTML::image('frontend/images/sp-loading.gif')}}<br>{{trans('front.loading_images')}}</div>
				<div class="sp-wrap">
                	@if($service->image)
                		<a href="{{url('uploads/'.$service->image)}}">{!!Helper::image2($service->image, [], false)!!}</a>
                	@endif
                	@foreach($service->images as $img)
                    	<a href="{{url('uploads/'.$img->image)}}">{!!Helper::image2($img->image, [], false)!!}</a>
                    @endforeach
                </div>
			</div>
			<div class="col-xs-12 col-md-8">
				<header><h1 class="hdr-styl-001" style="margin-top: 0">{{$service_lang->name}}</h1></header>
				<p class="nrml-p" style="margin-top: 10px;">
					{!!str_limit($service_lang->description, 500)!!}
				</p>
				<div class="table-responsive">
					<table class="table table-condensed inf-tbl">
						<tbody>
							<tr>
								<td style="width:140px;">{{trans('dash.price_range')}}:</td>
								<td>
									@if($service->price_min && $service->price_max)
										{{trans('front.from')}} {{$service->price_min}} {{trans('front.to')}} {{$service->price_max}}</a>
									@else
										{{trans('front.not_available')}}
									@endif
								</td>
							</tr>
							<tr>
								<td>{{trans('dash.expiry_date')}}:</td>
								<td>{{$service->expired_at}}</td>
							</tr>
							<tr>
								<td>{{trans('dash.request_location')}}:</td>
								<td>
									@if(count($service_locations)>0)
										@foreach($service_locations as $id)
											<a href="#" class="btn btn-xs btn-default">{{App\Country::get_country($id)->name}}</a>
										@endforeach
									@endif
								</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="cnct-inf-sid ad-pd">
					<h3 class="hdr-styl-004"><a href="#d">{{$profile->company_name}}</a> <span class="flg-ico">
					{!!User::flag($service->user,[],true)!!}</span></h3>

					<p class="sml-p-wth-spn">
						<span>{{trans('front.business_type')}}:</span>
						@if($business_types && is_array($business_types))
							@foreach($business_types as $type)
								{{trans('dash.business_types')[$type]}}, 
							@endforeach
						@endif
					</p>

					<div class="clnt-stt">
						<div><a href="javascript:void(0)"><i class="fa fa-info-circle nt-vrfid"></i></a> {{trans('front.not_verified')}}</div>
						<div><i class="fa fa-user"></i> {{$profile->first_name}} {{$profile->last_name}}</div>
						<a href="{{User::url_contact($service->user)}}" class="popup"><i class="fa fa-paper-plane bluu"></i> {{trans('front.contact_details')}}</a>
					</div>
                	<div class="options-col">
                    	<div>
                            <a><i class="fa fa-camera"></i></a>
                            <a href="#d"><i class="fa fa-film"></i></a>
                            <a href="{{User::url_contact($service->user)}}" class="popup"><i class="fa fa-info"></i></a>
                            <a href="#"><i class="fa fa-tag"></i></a>
                        </div>
                    </div>
				</div>

				<div class="shr-prnt-br02 row">
					<div class="col-xs-12 col-md-6 folow-us">
						<span>{{trans('front.share_us_on')}}:</span>
						<div style="display: inline-block;" class="addthis_inline_share_toolbox"></div>
					</div>
					<div class="col-xs-12 col-md-6 prnt-br text-right">
						<a href="{{Service::print_url($service)}}" target="_blank"><i class="fa fa-print"></i> {{trans('front.print')}}</a>
						<a href="#d"><i class="fa fa-envelope"></i> {{trans('front.product_add_email')}}</a>
						<a href="{{url('product/addtofavorites/'.$service->id.'/service')}}" class="popup"><i class="fa fa-heart"></i> {{trans('front.add_to_favorites')}}</a>
					</div>
				</div>
				
				<div class="lft-btn-hldr hidden">
					{!!Form::open(['url'=>'cart'])!!}
                        <input type="hidden" name="product_id" value="{{$service->id}}">
                        <button type="submit" class="grn-btn add-to-cart"><i class="fa fa-shopping-cart"></i> {{trans('front.request_for_quote')}}</button>
                    {!!Form::close()!!}
				</div>
			</div>
			<br class="clr-bth" />
			<a name="details"></a>
			<div id="tabs02" class="tabs02">
				<ul>
				    <li><a class="tab_nav" href="#tabs02-1">@lang('front.service_details')</a></li>
				    <li><a class="tab_nav" href="#tabs02-2">@lang('front.company_profile')</a></li>
				</ul>
				<div id="tabs02-1" class="product_details">
					<div class="row">
						<div class="col-md-12">
							{!!$service_lang->details!!}
						</div>
					</div>
				</div>
				<div id="tabs02-2">
				    {{$profile->company_name}}
				    <br>
				    <div class="lock_layer">
						<a href="{{url('interact/unlock?ref=contact_details&id=')}}" class="unlock_act popup"><i class="fa fa-unlock"></i> @lang('front.unlock_contact_details')</a>
					</div>
				    <div class="locked">
				    	<a href="{{User::url_contact($service->user)}}" class="popup btn btn-primary"><i class="fa fa-paper-plane"></i> {{trans('front.contact_details')}}</a>
				    </div>
				</div>
			</div>

			<a name="contact_supplier"></a>
			<div class="full-blk table-responsive">
				<legend>{{trans('front.contact_service_provider')}}</legend>
				{!!Form::open(['class'=>'form-horizontal', 'url'=>'services/enquiry'])!!}
					{!!Form::hidden('service_id', $service->id)!!}
					@if(Auth::check())
						<div class="col-md-6">
							<div class="form-group {{$errors->has('name')?'has-error':''}}">
								{!!Form::label('name', trans('front.from'), ['class'=>'col-md-3 control-label'])!!}
								<div class="col-md-8">
									<a href="{{User::url_contact(Auth::user())}}" class="popup">
										{{Auth::user()->name}} 
										@if(Auth::user()->profile)
											<br>{{Auth::user()->profile->company_name}}	
										@endif
									</a>
								</div>
							</div>
						</div>
					@else
						<div class="col-md-6">
							<div class="form-group">
								{!!Form::label('name',trans('front.name'), ['class'=>'col-md-3 control-label'])!!}
								<div class="col-md-8">
									{!!Form::text('name',null,['class'=>'form-control','placeholder'=>trans('front.ent_ur_name'),'required'=>'required'])!!}
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								{!!Form::label('email',trans('front.email'), ['class'=>'col-md-3 control-label'])!!}
								<div class="col-md-8">
									{!!Form::text('email',null,['class'=>'form-control','placeholder'=>trans('front.ent_ur_email'),'required'=>'required'])!!}
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								{!!Form::label('country',trans('front.country'), ['class'=>'col-md-3 control-label'])!!}
								<div class="col-md-8">
									{!!Form::select('country',$countries->lists('name','id'),$selected_country,['class'=>'form-control'])!!}
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								{!!Form::label('mobile',trans('front.mobile'), ['class'=>'col-md-3 control-label'])!!}
								<div class="col-md-8">
									{!!Form::text('mobile',null,['class'=>'form-control','placeholder'=>trans('front.ent_ur_mobile'),'required'=>'required'])!!}
								</div>
							</div>
						</div>
					@endif
					<div class="col-md-6">
						<div class="form-group">
							{!!Form::label('to',trans('front.send_to'), ['class'=>'col-md-3 control-label'])!!}
							<div class="col-md-8">
								<a href="{{User::url_contact($service->user)}}" class="popup">
									{{$service->user->name}}<br>
									<div class="help-block">{{$service->user->profile->company_name}}</div>
								</a>
							</div>
						</div>
					</div>
					<div class="col-md-12"></div>
					<div class="col-md-6">
						<div class="form-group">
							{!!Form::label('description',trans('front.description'), ['class'=>'col-md-3 control-label'])!!}
							<div class="col-md-8">
								{!!Form::textarea('description', null, ['class'=>'form-control', 'rows'=>'3'])!!}
							</div>
						</div>
					</div>
					<div class="col-md-12"></div>
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-md-offset-3 col-md-5">
								{!!Form::submit(trans('front.send_enquiry'), ['class'=>'btn btn-loading btn-warning'])!!}
							</div>
						</div>
					</div>
				{!!Form::close()!!}
			</div>

			<div class="full-blk table-responsive">
				<legend>{{trans('front.other_services')}}</legend>
				<div class="row lstng-stly-02">
					@foreach($other_services as $i_service)
						<?php $service_lang = Helper::lang_data($i_service, $lng_id); ?>
				        <figure class="col-xs-12 col-sm-6 col-md-3">
				            <div>
				                <a href="{{Service::url($i_service)}}" class="img-lnk-hldr">{{Service::Image($i_service)}}</a>
				                <figcaption>
				                    <div><a href="{{Service::url($i_service)}}">{{$service_lang->name}}</a></div>
				                </figcaption>
				            </div>
				        </figure>
				    @endforeach
			    </div>
			    <div class="lft-btn">
			    	<a href="{{url('services')}}" class="vw-mr-btn">{{trans('front.view_more')}}</a>
			    </div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('script')
	@include('dashboard.layouts.popup')
@endsection